# Generated by Django 3.2.5 on 2021-09-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='equipo',
        ),
    ]
