# Generated by Django 3.2.9 on 2021-11-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0002_remove_post_equipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postsecundaria',
            name='userSecu',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='votar',
            name='codigo_materia',
        ),
        migrations.RemoveField(
            model_name='votar',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostSecundaria',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Votar',
        ),
    ]
