# Generated by Django 3.2.9 on 2021-11-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0003_auto_20211109_1528'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clases',
            new_name='Grupos',
        ),
    ]
