# Generated by Django 3.2.9 on 2021-11-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0004_rename_clases_grupos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupos',
            old_name='nombre',
            new_name='grupo',
        ),
        migrations.RemoveField(
            model_name='grupos',
            name='tema',
        ),
        migrations.AddField(
            model_name='grupos',
            name='institucion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grupos',
            name='materia',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
