# Generated by Django 3.2.5 on 2021-11-23 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0007_equipos_temas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipos',
            old_name='codigo',
            new_name='codigo_materia',
        ),
        migrations.CreateModel(
            name='Asignar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.equipos')),
                ('id_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.temas')),
            ],
        ),
    ]
