# Generated by Django 3.2.5 on 2021-11-25 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AMCE', '0006_usertype'),
        ('AMCE', '0009_pertenecer'),
    ]

    operations = [
    ]
